version: '1.1.8'
services:
  wukongim:
    container_name: ${CONTAINER_NAME}
    image: registry.cn-shanghai.aliyuncs.com/wukongim/wukongim:v1.1.8
    restart: always
    ports:
      - "${PANEL_APP_PORT_WK_API}:5001"
      - "${PANEL_APP_PORT_WK_TCP}:5100"
      - "${PANEL_APP_PORT_WK_WS}:5200"
      - "${PANEL_APP_PORT_HTTP}:5300"
      - "${PANEL_APP_PORT_WK_DEMO_SERVER}:5172"
    volumes:
      - ./wukongim:/root/wukongim
    environment:
      - WK_MODE=release
      - WK_EXTERNAL_IP=${EXTERNAL_IP}
      - WK_CONVERSATION_ON=true
      - WK_WEBHOOK_GRPCADDR=tangsengdaodaoserver:6979
      - WK_DATASOURCE_ADDR=http://tangsengdaodaoserver:8090/v1/datasource
      - WK_DATASOURCE_CHANNELINFOON=true
      - WK_TOKENAUTHON=true
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true
